# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /C:/Users/MY PC/REPO/hiring/devops-engineer/assignment

##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /C:/Users/MY PC/REPO/hiring/devops-engineer/assignment /C:/Users/MY PC/REPO/hiring/devops-engineer/assignment/

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/C:/Users/MY PC/REPO/hiring/devops-engineer/assignment"]